name: release
on:
  push:
    tags:
      - "v*"

jobs:
  release:
    name: publish releases
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Golang
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"
      - name: Build Golang binary & Replace version
        run: make build && make version
      - name: Build Arch Linux Package
        uses: 2m/arch-pkgbuild-builder@v1.18
        with:
          target: "pkgbuild"
          pkgname: "release"
      - name: Upload to release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            release/wah*
            release/domains
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
